Garlic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("shop.urls")),
              ] + static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about_us, name="about"),
    path('contact-us/', views.contact_us, name="contact_us"),
]

shop/models.py
from django.db import models

# Create your models here.

shop/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    return render(request, 'shop/index.html')


def about_us(request):
    return render(request, 'shop/about.html')


def contact_us(request):
    return render(request, 'shop/contact_us.html')

templates/shop/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Garlic || Shop ||</title>

{#    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/favicons/apple-touch-icon.png' %}">#}
{#    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/favicons/favicon-32x32.png' %}">#}
{#    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/favicons/favicon-16x16.png' %}">#}
    <link rel="manifest" href="{% static 'assets/images/favicons/site.webmanifest' %}">
    <meta name="description" content="Garlic shop">

{#    <link rel="preconnect" href="https://fonts.gstatic.com/">#}
    <link href="https://fonts.googleapis.com/css2?family=Handlee&amp;family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
          rel="stylesheet">

    <!-- CSS here -->
        <link rel="stylesheet" href="{% static 'assets2/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'assets2/css/responsive.css' %}">



    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/odometer.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jarallax.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/agrikon-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nouislider.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nouislider.pips.css' %}">

    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
</head>
<body>
<div class="preloader">
    <img class="preloader__image" width="205" src="{% static 'assets/images/garlic_logo.png' %}" alt="">
</div>
<div class="page-wrapper">
    <header class="main-header">
        <div class="topbar">
            <div class="container">
                <div class="topbar__left">
                    <div class="topbar__social">
                        <a href="##" class="fab fa-facebook-square"></a>
                        <a href="##" class="fab fa-twitter"></a>
                        <a href="##" class="fab fa-pinterest-p"></a>
                        <a href="##" class="fab fa-instagram"></a>
                    </div>
                    <p>Welcome to Garlic Shop</p>
                </div>
                <div class="topbar__right">
                    <a href="##"><i class="agrikon-icon-email"></i>
                        <span >example@mail.com</span></a>
                    <a href="##"><i class="agrikon-icon-clock"></i>Mon - Sat 8:00 - 6:30, Sunday - CLOSED</a>
                </div>
            </div>
        </div>
        <nav class="main-menu">
            <div class="container">
                <div class="logo-box">
                    <a href="{% url 'shop:home' %}" aria-label="logo image"><img src="{% static 'assets/images/garlic_logo.png' %}" width="103" alt=""></a>
                    <span class="fa fa-bars mobile-nav__toggler"></span>
                </div>
                <ul class="main-menu__list">
                    <li>
                        <a href="{% url 'shop:home' %}">Home  </a>
                    </li>
                    <li>
                        <a href="{% url 'shop:about' %}">About</a>
                    </li>
                    <li>
                        <a href="{% url 'shop:contact_us' %}">Contact Us</a>
                    </li>
                </ul>

                <div class="main-header__info">
                    <a href="##" class="search-toggler main-header__search-btn main-header__cart-btn">
                        <i class="agrikon-icon-magnifying-glass"></i></a>
                    <a href="#" class="main-header__info-phone">
                        <i class="agrikon-icon-phone-call"></i>
                        <span class="main-header__info-phone-content">
                            <span class="main-header__info-phone-text">Call Anytime</span>
                            <span class="main-header__info-phone-title">91 111 222 3333</span>
                        </span>
                    </a>
                </div>
            </div>
        </nav>

    </header>

    {% block page_container %}

    {% endblock %}




    <footer class="site-footer">
        <img src="{% static 'assets/images/icons/footer-bg-icon-1.png' %}" class="site-footer__shape-1" alt="">
        <img src="{% static 'assets/images/icons/footer-bg-icon-2.png' %}" class="site-footer__shape-2" alt="">

            <div class="">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6 col-lg-6 col-xl-4">
                    <div class="footer-widget">
                        <a href="{% url 'shop:home' %}" class="footer-widget__Logo">
                            <img src="{% static 'assets/images/garlic_logo.png' %}" width="153" alt="">
                        </a>
                        <p>There are many variations of passages of lorem ipsum available, but the majority suffered.
                        </p>
                        <form action="#" data-url="YOUR_MAILCHIMP_URL" class="mc-form">
                            <input type="email" name="EMAIL" placeholder="Email Address">
                            <button type="submit"><i class="agrikon-icon-right-arrow"></i></button>
                        </form>
                        <div class="mc-form__response"></div>
                        <div class="footer__social">
                            <a href="##" class="fab fa-facebook-square"></a>
                            <a href="##" class="fab fa-twitter"></a>
                            <a href="##" class="fab fa-pinterest-p"></a>
                            <a href="##" class="fab fa-instagram"></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6 col-xl-2">
                    <div class="footer-widget footer-widget__links-widget">
                        <h3 class="footer-widget__title">Links</h3>
                        <ul class="list-unstyled footer-widget__links">
                            <li><a href="##">Our Projects</a></li>
                            <li><a href="{% url 'shop:home' %}">About us</a></li>
                            <li><a href="##">New Campaign</a></li>
                            <li><a href="##">Upcoming Events</a></li>
                            <li><a href="##">Volunteers</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6 col-xl-3">
                    <div class="footer-widget">
                        <h3 class="footer-widget__title">News</h3>
                        <ul class="list-unstyled footer-widget__post">
                            <li>
                                <img src="{% static 'assets/images/resources/footer-post-1.png' %}" alt="">
                                <div class="footer-widget__post-content">
                                    <span>Nov 16, 2020</span>
                                    <h4><a href="#">How to grow vagetables in the forms</a></h4>
                                </div>
                            </li>
                            <li>
                                <img src="{% static 'assets/images/resources/footer-post-2.png' %}" alt="">
                                <div class="footer-widget__post-content">
                                    <span>Nov 16, 2020</span>
                                    <h4><a href="#">How to grow vagetables in the forms</a></h4>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6 col-xl-3">
                    <h3 class="footer-widget__title">Contact</h3>
                    <ul class="list-unstyled footer-widget__contact">
                        <li>
                            <i class="agrikon-icon-telephone"></i>
                            <a href="#">111 222 3333</a>
                        </li>
                        <li>
                            <i class="agrikon-icon-email"></i>
                            <a href="#"><span
                                    class="__cf_email__">example@mail.com</span></a>
                        </li>
                        <li>
                            <i class="agrikon-icon-pin"></i>
                            <a href="##">80 broklyn golden street line
                                New York, USA</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
                <div class="footer-bottom-shape fb-shape1 running"><img src="{% static 'assets2/img/images/footer_vector01.png' %}" alt=""></div>
                <div class="footer-bottom-shape fb-shape2"><img src="{% static 'assets2/img/images/footer_vector02.png' %}" alt=""></div>
                <div class="footer-bottom-shape fb-shape3"><img src="{% static 'assets2/img/images/footer_vector03.png" class="rotateme' %}" alt=""></div>
            </div>
    </footer>
    <div class="bottom-footer">
        <div class="container">
            <p>© Copyright 2020 by Company.com</p>
            <div class="bottom-footer__links">
                <a href="##">Terms & Conditions</a>
                <a href="##">Privacy Policy</a>
                <a href="##">Sitemap</a>
            </div>
        </div>
    </div>

</div>

<div class="mobile-nav__wrapper">
    <div class="mobile-nav__overlay mobile-nav__toggler"></div>

    <div class="mobile-nav__content">
        <span class="mobile-nav__close mobile-nav__toggler"><i class="far fa-times"></i></span>
        <div class="logo-box">
            <a href="#index-2.html" aria-label="logo image"><img src="{% static 'assets/images/garlic_logo.png' %}" width="155" alt=""/></a>
        </div>

        <div class="mobile-nav__container"></div>

        <ul class="mobile-nav__contact list-unstyled">
            <li>
                <i class="agrikon-icon-email"></i>
                <a href="#"><span
                        class="__cf_email__">example@mail.com</span></a>
            </li>
            <li>
                <i class="agrikon-icon-telephone"></i>
                <a href="#">111 222 3333</a>
            </li>
        </ul>
        <div class="mobile-nav__top">

            <div class="mobile-nav__social">
                <a href="##" aria-label="twitter"><i class="fab fa-twitter"></i></a>
                <a href="##" aria-label="facebook"><i class="fab fa-facebook-square"></i></a>
                <a href="##" aria-label="pinterest"><i class="fab fa-pinterest-p"></i></a>
                <a href="##" aria-label="instagram"><i class="fab fa-instagram"></i></a>
            </div>
        </div>
    </div>

</div>

<div class="search-popup">
    <div class="search-popup__overlay search-toggler"></div>

    <div class="search-popup__content">
        <form action="#">
            <label for="search" class="sr-only">search here</label>
            <input type="text" id="search" placeholder="Search Here..."/>
            <button type="submit" aria-label="search submit" class="thm-btn">
                <i class="fa fa-search"></i>
            </button>
        </form>
    </div>

</div>
<a href="##" data-target="html" class="scroll-to-target scroll-to-top"><i class="fa fa-angle-up"></i></a>
<script src="{% static 'assets/js/jquery-3.5.1.min.js'  %}"></script>
<script src="{% static 'assets/js/bootstrap.bundle.min.js'  %}"></script>
<script src="{% static 'assets/js/swiper.min.js'  %}"></script>
<script src="{% static 'assets/js/jquery.ajaxchimp.min.js'  %}"></script>
<script src="{% static 'assets/js/jquery.magnific-popup.min.js'  %}"></script>
<script src="{% static 'assets/js/jquery.validate.min.js'  %}"></script>
<script src="{% static 'assets/js/bootstrap-select.min.js'  %}"></script>
<script src="{% static 'assets/js/wow.js'  %}"></script>
<script src="{% static 'assets/js/odometer.min.js'  %}"></script>
<script src="{% static 'assets/js/jquery.appear.min.js'  %}"></script>
<script src="{% static 'assets/js/jarallax.min.js'  %}"></script>
<script src="{% static 'assets/js/circle-progress.min.js'  %}"></script>
<script src="{% static 'assets/js/wNumb.min.js'  %}"></script>
<script src="{% static 'assets/js/nouislider.min.js'  %}"></script>

<script src="{% static 'assets/js/theme.js' %}"></script>
</body>

</html>

templates/shop/contact_us.html
{% extends 'shop/base/base.html' %}
{% load static %}
{% block page_container %}


    <div class="stricky-header stricked-menu main-menu">
        <div class="sticky-header__content"></div>
    </div>
    <section class="page-header">
        <div class="page-header__bg"
             style="background-image: url({% static 'assets/images/backgrounds/page-header-bg-1-1.jpg' %});"></div>

        <div class="container">
            <ul class="thm-breadcrumb list-unstyled">
                <li><a href="{% url 'shop:home' %}">Home</a></li>
                <li>/</li>
                <li><span>Contact Us</span></li>
            </ul>
            <h2>Contact</h2>
        </div>
    </section>
    <section class="contact-one">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-6 col-xl-4">
                    <div class="contact-one__content">
                        <div class="block-title">
                            <div class="block-title__image"></div>
                            <p>Contact now</p>
                            <h3>Leave A Message</h3>
                        </div>
                        <div class="contact-one__summery">
                            <p>Lorem ipsum dolor sit amet, consectetur notted adipisicing elit sed do eiusmod tempor
                                incididunt ut labore et dolore magna aliqua lonm andhn. Aenean tincidunt id mauris id
                                auctor. Donec at ligula lacus dignissim mi quis simply neque.</p>
                        </div>
                        <div class="contact-one__social">
                            <a href="#"><i class="fab fa-facebook-square"></i></a>
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-6 col-xl-8">
                    <form action="#"
                          class="contact-one__form contact-form-validated">
                        <div class="row">
                            <div class="col-lg-6">
                                <input type="text" name="name" placeholder="Full Name">
                            </div>
                            <div class="col-lg-6">
                                <input type="text" name="email" placeholder="Email Address">
                            </div>
                            <div class="col-lg-6">
                                <input type="text" name="phone" placeholder="Phone Number">
                            </div>
                            <div class="col-lg-6">
                                <input type="text" name="subject" placeholder="Subject">
                            </div>
                            <div class="col-lg-12">
                                <textarea name="message" placeholder="Write Message"></textarea>
                            </div>
                            <div class="col-lg-12">
                                <button type="submit" class="thm-btn">Send a Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="contact-infos">
        <div class="container">
            <div class="inner-container wow fadeInUp" data-wow-duration="1500ms">
                <div class="row no-gutters">
                    <div class="col-sm-12 col-md-12 col-lg-4">
                        <div class="contact-infos__single">
                            <h3>About Company</h3>
                            <p>Lorem ipsum dolor sit amet consectetur adipiscing elit nulla sit amet lectus neque.</p>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-4">
                        <div class="contact-infos__single">
                            <h3>Visit Company</h3>
                            <p>Indore MP India.</p>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-4">
                        <div class="contact-infos__single">
                            <h3>Call or Email</h3>
                            <p>
                                <a href="#">company.com</a><br>
                                <a href="#">example@mail.com</a>
                                <br>
                                <a href="#">111 222 3333</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="google-map__home-two">
        <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d235526.9092476714!2d75.72376205026237!3d22.72422842958636!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3962fcad1b410ddb%3A0x96ec4da356240f4!2sIndore%2C%20Madhya%20Pradesh!5e0!3m2!1sen!2sin!4v1624883823275!5m2!1sen!2sin"
                class="map__home-two" allowfullscreen></iframe>
    </div>



{% endblock %}